name: onelga_local_services
description: Onelga Local Services Mobile App - Flutter application for accessing local government services
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication
  local_auth: ^2.1.6
  crypto: ^3.0.3

  # File Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1

  # Maps & Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Notifications
  flutter_local_notifications: ^16.2.0
  firebase_messaging: ^14.7.9

  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: OnelgaCustom
      fonts:
        - asset: assets/fonts/OnelgaCustom-Regular.ttf
        - asset: assets/fonts/OnelgaCustom-Bold.ttf
          weight: 700
